name: Test

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Run tests
        run: npm run test
